### ISSUE TITLE
Is this displayed on the LED matrix or on the Raspberry Pi Rapsberry GUI?

### ISSUE THREAD

**Issue by EmbeddedSam** [astro-pi/apollo-soyuz#1]
I am getting this error when trying to run this example on the pi 2 with the sense Hat

Traceback (most recent call last):
  File "soyuz.py", line 8, in <module>
    display = pi3d.Display.create()
  File "/usr/local/lib/python3.2/dist-packages/pi3d/Display.py", line 510, in create
    display = Display(tkwin, use_pygame)
  File "/usr/local/lib/python3.2/dist-packages/pi3d/Display.py", line 144, in **init**
    self.opengl = DisplayOpenGL()
  File "/usr/local/lib/python3.2/dist-packages/pi3d/util/DisplayOpenGL.py", line 31, in **init**
    assert s >= 0
AssertionError

**Comment by EmbeddedSam** [comment]
I should say that I have SSH'd into the Pi through PuTTY I am not running it with a local screen and keyboard. Just wanted a good finished demo on the LED matrix of Roll,Pitch and Yaw

**Comment by XECDesign** [comment]
Nope, this doesn't touch the LED matrix.
